language: php

php:
    - 5.5

env:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.8.*

before_script: composer install --dev

script: ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls
