language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 7.0

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_script: composer install --dev

script: ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls
