language: php

php:
    - 5.5
    - 5.4
    - 5.3

env:
    - SYMFONY_VERSION=2.6.*

before_script: composer install --dev

script: ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls
